name: CD on the self-hosted server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the deploy script
        run: ./deploy.sh
